name: Full Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu_build:
    name: Build on Ubuntu with tests
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-ubuntu
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.0.6'

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      # TODO: Remove dev central flag once scan tool is published to central
      - name: Install scan tool
        env:
          BALLERINA_DEV_CENTRAL: true
        run: bal tool pull scan

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build --scan

  windows_build:
    name: Build on Windows with tests
    runs-on: windows-latest
    concurrency:
      group: ${{ github.head_ref }}-windows
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: '2201.9.1'

      # TODO: Remove dev central flag once scan tool is published
      - name: Install scan tool
        env:
          BALLERINA_DEV_CENTRAL: true
        run: bal tool pull scan

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build --scan
